export const GLOBALTYPES = {
    AUTH: 'AUTH',
    ALERT: 'ALERT',
    LOGOUT: 'LOGOUT',
    STORELOCATION: 'STORELOCATION',
    LOADDISH: 'LOADDISH',
    LOADCATE: 'LOADCATE',
    LOADAREAS: 'LOADAREAS',
};
