const constants = {
    USER_ALL_REQUEST: 'USER_ALL_REQUEST',
    USER_ALL_SUCCESS: 'USER_ALL_SUCCESS',
    USER_ALL_FAIL: 'USER_ALL_FAIL',

    USER_DETAIL_REQUEST: 'USER_DETAIL_REQUEST',
    USER_DETAIL_SUCCESS: 'USER_DETAIL_SUCCESS',
    USER_DETAIL_FAIL: 'USER_DETAIL_FAIL',

    USER_CREATE_REQUEST: 'USER_CREATE_REQUEST',
    USER_CREATE_SUCCESS: 'USER_CREATE_SUCCESS',
    USER_CREATE_FAIL: 'USER_CREATE_FAIL',
    USER_CREATE_RESET: 'USER_CREATE_RESET',

    USER_UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
    USER_UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
    USER_UPDATE_FAIL: 'USER_UPDATE_FAIL',
    USER_UPDATE_RESET: 'USER_UPDATE_RESET',

    USER_DELETE_REQUEST: 'USER_DELETE_REQUEST',
    USER_DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
    USER_DELETE_FAIL: 'USER_DELETE_FAIL',
    USER_DELETE_RESET: 'USER_DELETE_RESET',
};

export default constants;
