const constants = {
    AREAS_ALL_REQUEST: 'AREAS_ALL_REQUEST',
    AREAS_ALL_SUCCESS: 'AREAS_ALL_SUCCESS',
    AREAS_ALL_FAIL: 'AREAS_ALL_FAIL',

    AREAS_DETAIL_REQUEST: 'AREAS_DETAIL_REQUEST',
    AREAS_DETAIL_SUCCESS: 'AREAS_DETAIL_SUCCESS',
    AREAS_DETAIL_FAIL: 'AREAS_DETAIL_FAIL',

    AREAS_CREATE_REQUEST: 'AREAS_CREATE_REQUEST',
    AREAS_CREATE_SUCCESS: 'AREAS_CREATE_SUCCESS',
    AREAS_CREATE_FAIL: 'AREAS_CREATE_FAIL',
    AREAS_CREATE_RESET: 'AREAS_CREATE_RESET',

    AREAS_UPDATE_REQUEST: 'AREAS_UPDATE_REQUEST',
    AREAS_UPDATE_SUCCESS: 'AREAS_UPDATE_SUCCESS',
    AREAS_UPDATE_FAIL: 'AREAS_UPDATE_FAIL',
    AREAS_UPDATE_RESET: 'AREAS_UPDATE_RESET',

    AREAS_DELETE_REQUEST: 'AREAS_DELETE_REQUEST',
    AREAS_DELETE_SUCCESS: 'AREAS_DELETE_SUCCESS',
    AREAS_DELETE_FAIL: 'AREAS_DELETE_FAIL',
    AREAS_DELETE_RESET: 'AREAS_DELETE_RESET',

    AREAS_ID_REQUEST: 'TABLE_ALL_REQUEST',
    AREAS_ID_SUCCESS: 'TABLE_ALL_SUCCESS',
    AREAS_ID_FAIL: 'TABLE_ALL_FAIL',

    TABLE_ALL_REQUEST: 'TABLE_ALL_REQUEST',
    TABLE_ALL_SUCCESS: 'TABLE_ALL_SUCCESS',
    TABLE_ALL_FAIL: 'TABLE_ALL_FAIL',

    TABLE_DETAIL_REQUEST: 'TABLE_DETAIL_REQUEST',
    TABLE_DETAIL_SUCCESS: 'TABLE_DETAIL_SUCCESS',
    TABLE_DETAIL_FAIL: 'TABLE_DETAIL_FAIL',

    TABLE_CREATE_REQUEST: 'TABLE_CREATE_REQUEST',
    TABLE_CREATE_SUCCESS: 'TABLE_CREATE_SUCCESS',
    TABLE_CREATE_FAIL: 'TABLE_CREATE_FAIL',
    TABLE_CREATE_RESET: 'TABLE_CREATE_RESET',

    TABLE_UPDATE_REQUEST: 'TABLE_UPDATE_REQUEST',
    TABLE_UPDATE_SUCCESS: 'TABLE_UPDATE_SUCCESS',
    TABLE_UPDATE_FAIL: 'TABLE_UPDATE_FAIL',
    TABLE_UPDATE_RESET: 'TABLE_UPDATE_RESET',

    TABLE_DELETE_REQUEST: 'TABLE_DELETE_REQUEST',
    TABLE_DELETE_SUCCESS: 'TABLE_DELETE_SUCCESS',
    TABLE_DELETE_FAIL: 'TABLE_DELETE_FAIL',
    TABLE_DELETE_RESET: 'TABLE_DELETE_RESET',
};

export default constants;
