const constants = {
    AREAS_ALL_REQUEST: 'AREAS_ALL_REQUEST',
    AREAS_ALL_SUCCESS: 'AREAS_ALL_SUCCESS',
    AREAS_ALL_FAIL: 'AREAS_ALL_FAIL',

    AREAS_DETAIL_REQUEST: 'AREAS_DETAIL_REQUEST',
    AREAS_DETAIL_SUCCESS: 'AREAS_DETAIL_SUCCESS',
    AREAS_DETAIL_FAIL: 'AREAS_DETAIL_FAIL',

    AREAS_CREATE_REQUEST: 'AREAS_CREATE_REQUEST',
    AREAS_CREATE_SUCCESS: 'AREAS_CREATE_SUCCESS',
    AREAS_CREATE_FAIL: 'AREAS_CREATE_FAIL',
    AREAS_CREATE_RESET: 'AREAS_CREATE_RESET',

    AREAS_UPDATE_REQUEST: 'AREAS_UPDATE_REQUEST',
    AREAS_UPDATE_SUCCESS: 'AREAS_UPDATE_SUCCESS',
    AREAS_UPDATE_FAIL: 'AREAS_UPDATE_FAIL',
    AREAS_UPDATE_RESET: 'AREAS_UPDATE_RESET',

    AREAS_DELETE_REQUEST: 'AREAS_DELETE_REQUEST',
    AREAS_DELETE_SUCCESS: 'AREAS_DELETE_SUCCESS',
    AREAS_DELETE_FAIL: 'AREAS_DELETE_FAIL',
    AREAS_DELETE_RESET: 'AREAS_DELETE_RESET',
};

export default constants;
