const constants = {
    CUSTOMER_ALL_REQUEST: 'CUSTOMER_ALL_REQUEST',
    CUSTOMER_ALL_SUCCESS: 'CUSTOMER_ALL_SUCCESS',
    CUSTOMER_ALL_FAIL: 'CUSTOMER_ALL_FAIL',

    CUSTOMER_DETAIL_REQUEST: 'CUSTOMER_DETAIL_REQUEST',
    CUSTOMER_DETAIL_SUCCESS: 'CUSTOMER_DETAIL_SUCCESS',
    CUSTOMER_DETAIL_FAIL: 'CUSTOMER_DETAIL_FAIL',

    CUSTOMER_CREATE_REQUEST: 'CUSTOMER_CREATE_REQUEST',
    CUSTOMER_CREATE_SUCCESS: 'CUSTOMER_CREATE_SUCCESS',
    CUSTOMER_CREATE_FAIL: 'CUSTOMER_CREATE_FAIL',
    CUSTOMER_CREATE_RESET: 'CUSTOMER_CREATE_RESET',

    CUSTOMER_UPDATE_REQUEST: 'CUSTOMER_UPDATE_REQUEST',
    CUSTOMER_UPDATE_SUCCESS: 'CUSTOMER_UPDATE_SUCCESS',
    CUSTOMER_UPDATE_FAIL: 'CUSTOMER_UPDATE_FAIL',
    CUSTOMER_UPDATE_RESET: 'CUSTOMER_UPDATE_RESET',

    CUSTOMER_DELETE_REQUEST: 'CUSTOMER_DELETE_REQUEST',
    CUSTOMER_DELETE_SUCCESS: 'CUSTOMER_DELETE_SUCCESS',
    CUSTOMER_DELETE_FAIL: 'CUSTOMER_DELETE_FAIL',
    CUSTOMER_DELETE_RESET: 'CUSTOMER_DELETE_RESET',
};

export default constants;
