const constants = {
    DISHES_ALL_REQUEST: 'DISHES_ALL_REQUEST',
    DISHES_ALL_SUCCESS: 'DISHES_ALL_SUCCESS',
    DISHES_ALL_FAIL: 'DISHES_ALL_FAIL',

    DISHES_DETAIL_REQUEST: 'DISHES_DETAIL_REQUEST',
    DISHES_DETAIL_SUCCESS: 'DISHES_DETAIL_SUCCESS',
    DISHES_DETAIL_FAIL: 'AREASR_DETAIL_FAIL',

    DISHES_CREATE_REQUEST: 'DISHES_CREATE_REQUEST',
    DISHES_CREATE_SUCCESS: 'DISHES_CREATE_SUCCESS',
    DISHES_CREATE_FAIL: 'DISHES_CREATE_FAIL',
    DISHES_CREATE_RESET: 'DISHES_CREATE_RESET',

    DISHES_UPDATE_REQUEST: 'DISHES_UPDATE_REQUEST',
    DISHES_UPDATE_SUCCESS: 'DISHES_UPDATE_SUCCESS',
    DISHES_UPDATE_FAIL: 'DISHES_UPDATE_FAIL',
    DISHES_UPDATE_RESET: 'DISHES_UPDATE_RESET',

    DISHES_DELETE_REQUEST: 'DISHES_DELETE_REQUEST',
    DISHES_DELETE_SUCCESS: 'DISHES_DELETE_SUCCESS',
    DISHES_DELETE_FAIL: 'DISHES_DELETE_FAIL',
    DISHES_DELETE_RESET: 'DISHES_DELETE_RESET',
};

export default constants;
